### ISSUE TITLE
Add race_unk back to demo tables

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/claims_data#10]

**Comment by alastairmatheson** [comment]
I didn't do this with the August update but will try and get it done before processing the September data

**Comment by dcolombara** [comment]
done for [PHClaims].[stage].[mcare_elig_demo]

**Comment by alastairmatheson** [comment]
Addressed with https://github.com/PHSKC-APDE/claims_data/pull/51
Added race_unk and race_eth_unk to mcaid_elig_demo
