### ISSUE TITLE
cov_time_day missing 1 day

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/claims_data#106]
looking at the mcaid_mcare_elig_timevar table, it appears to me that the cov_time_day variable is short by 1 day. look at id_apde = 2390. shouldn't the value be 5 days instead of 4? because we include the last day in the calculation. note that the claims_elig function of the claims package appears to be calculating this correctly, but just wanted to flag it for correction in the table itself.

**Comment by dcolombara** [comment]
@preason66 … good catch! Thanks for pointing this out. I'll fix this momentarily.
