### ISSUE TITLE
recode geo_kc flag to match approved method

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/claims_data#107]
Just creating an issue to note that we still have to recode the geo_kc flag so that it matches our approved method (https://kc1.sharepoint.com/:x:/r/teams/KingCountyCross-SectorData/Shared%20Documents/References/Geographic%20definitions/King%20County%20definition%20for%20claims_7.7.19.xlsx?d=w111d279f60bd4adbabea68b91440a3d1&csf=1&e=nfJJVe).

SQL code for the recoded geo_kc flag could be gleaned from my following code, looking at the geo_kc_2 variable:

SELECT *
	case
		when geo_county_code is not null and geo_county_code = '033' then 1
		when geo_county_code is null and b.geo_kc = 1 then 1
		else 0
	end as geo_kc_2
into #temp1
from PHClaims.final.mcaid_mcare_elig_timevar as a
left join PHClaims.ref.geo_kc_zip as b
on a.geo_zip = b.geo_zip;

**Comment by dcolombara** [comment]
@preason66 … thanks for this. I've updated the code and am rerunning right now. I'll also ensure that parallel changes are made in the housing repo and will update the timevar there as well. 

@alastairmatheson … I don't think there is anything for you to do on this issue. I'll close it when I submit a pull request later.
