### ISSUE TITLE
top_causes function needs additional testing

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/claims_data#113]
I updated the top_causes function to work with other data sources. However, I only had time to test against the mcaid_mcare table. Additional testing would be useful for APCD and mcaid-/mcare-only tables. I made a few other changes that might have bugs too.

**Comment by alastairmatheson** [comment]
This is a low priority though, only next time you need to use the function.

**Comment by kai-fukutaki** [comment]
Resolved for medicaid and APCD sources via https://github.com/PHSKC-APDE/claims_data/pull/146 

New medicare data is not in yet, but I'm going to mark this as done for now with the knowledge that many functions will need updates when new medicare data drops
