### ISSUE TITLE
geo_kc in elig and timevar tables causes duplication when pulling a cohort

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/claims_data#20]
The mcare_elig_demo table has a kc_geo field to indicate if a person was ever in KC and the mcare_elig_timevar has a kc_geo field to indicator if a person was in KC for that particular time period. When running the cohort function, both fields are pulled into a single table but will have the same name.
Two options for resolution:
1) Rename kc_geo from the demo table to kc_geo_ever on the fly as the cohort function runs.
2) Rename kc_geo to kc_geo_ever in the demo table permanently.

**Comment by dcolombara** [comment]
I'll rename kc_geo to kc_geo_ever in the demo table permanently … probably by the end of today.
