### ISSUE TITLE
Rename geo fields in mcaid timevar

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/claims_data#21]
Remove the _clean suffixes from all address fields.
Rename geo_countyfp10 to geo_county_code?
Also rename geo_tractce10 to geo_tract_code, geo_hra_id to geo_hra_code, and geo_school_geoid10 to geo_school_code?

**Comment by alastairmatheson** [comment]
Also need to do this for the mcaid_mcare tables @dcolombara

**Comment by dcolombara** [comment]
I've updated the mcaid_mcare_elig_timevar. @alastairmatheson, when you've made your changes, you can close this issue.

**Comment by alastairmatheson** [comment]
Completed for stage./final.mciad_elig_timevar github.com/PHSKC-APDE/claims_data/commit/9f9190b981a0911e59306bf027a8ae8091e5709c). Need to decide if we want to change in ref.address_geocode in the future.
