### ISSUE TITLE
Add fields to mcaid_mcare_elig_timevar to indicate which program a person was in

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/claims_data#23]
I realized there's no obvious way to tell if a person was enrolled in Medicaid, Medicare, or both for a given time period in the mcaid_mcare_elig_timevar table. It can be deduced by looking at dual, part_a/b/c, and bsp_group_name/cov_type, but it might be easier if there were flags that did that work already (could be called _mcaid_ and _mcare_)

Thoughts?

**Comment by elikern-kc** [comment]
That makes sense to me as well.

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>
