### ISSUE TITLE
Truncating tables, using the loader package 

### ISSUE THREAD

**Issue by seh315** [PHSKC-APDE/claims_data#24]
When I use the loader package my table is truncated. According to Stata i should have (58 vars, 1,252,045 obs). In R & SQL I have 1,252,037 rows copied for this table: [PHClaims].[load_raw].[mcare_dme_claims_k_15]. I checked in Stata and there are no empty rows.

**Comment by elikern-kc** [comment]
Are there duplicate rows that somehow the loader package is flagging for removal?

Eli Kern, Epidemiologist, Public Health -Seattle & King County
________________________________

**Comment by seh315** [comment]
No duplicates according to Stata

**Comment by alastairmatheson** [comment]
Can you export the Stata table somewhere secure and pull it into R for comparison?

**Comment by seh315** [comment]
Yes I can save it in the medicare secure folder

**Comment by alastairmatheson** [comment]
> Yes I can save it in the medicare secure folder

In case you need some help getting the Stata file into R: https://github.com/PHSKC-APDE/R_training/blob/master/examples/example_import_export.md#stata-files

**Comment by seh315** [comment]
I was able to pull it into R has a .dta file. It matches the same number of variables and  observations (58 vars, 1,252,045 obs).

**Comment by alastairmatheson** [comment]
Can you now do some comparisons with the R file (1,252,037 rows) to see what the difference is?

**Comment by seh315** [comment]
Hi, so one issue I found so far is that this "\n" is being added to bene_id in the loader function. bene_id is the first variable so, I think it has something to do with how returns at the end of a row are specified.

**Comment by elikern-kc** [comment]
Susan – thanks, can you please email me your current script and two yaml files? I’ll test on my end. Thanks!

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by seh315** [comment]
Hi Eli,

Here’s the code and yaml files. I added the script I used to compare the datasets.

Thanks,
Susan

**Comment by elikern-kc** [comment]
Hmm – I don’t see any files in the email!

Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by alastairmatheson** [comment]
Is this issue closed now? @seh315

**Comment by elikern-kc** [comment]
Yes – I think so!

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by seh315** [comment]
Yes
