### ISSUE TITLE
Let's reconsider using bsp_group_cid instead of bsp_group_name in elig_timevar

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/claims_data#36]
I'm not thrilled about having a long text field in the elig_timevar table - could we just use bsp_group_cid instead?

**Comment by alastairmatheson** [comment]
Fixed for mcaid_elig_timevar in https://github.com/PHSKC-APDE/claims_data/commit/205df7abf4d0a7786b221ddbffef0ba53aa4ce83, https://github.com/PHSKC-APDE/claims_data/commit/205df7abf4d0a7786b221ddbffef0ba53aa4ce83, https://github.com/PHSKC-APDE/claims_data/commit/817aae256e3d6b663d4a3a6ca2bd2c53d4b26b41, https://github.com/PHSKC-APDE/claims_data/commit/52b7242d298399fec9368163693412c493e98f4e, and https://github.com/PHSKC-APDE/claims_data/commit/500e80e09f015c675f34bd4b01df611004a5d353 (yes it took a few goes to get right)

**Comment by alastairmatheson** [comment]
@dcolombara In case you're working on the mcaid_mcare tables in the near future.

**Comment by alastairmatheson** [comment]
Also changed for mcaid_mcare_pha with https://github.com/PHSKC-APDE/Housing/commit/1624d748c14e3e0aa759e5dc0ea34f8b102c751d

**Comment by alastairmatheson** [comment]
Changed for mcaid_mcare tables in https://github.com/PHSKC-APDE/claims_data/pull/67

**Comment by alastairmatheson** [comment]
Also fixed for claims_elig function in https://github.com/PHSKC-APDE/claims_data/pull/67/commits/f68da8c3f61c177362ff312a9cdfcb30a2189a83
