### ISSUE TITLE
Add all component vars to combined mcaid_mcare_elig tables

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/claims_data#43]
Right now the elig_timevar tables have an apde_dual field, which signifies when we observed people to be concurrently enrolled in Medicaid and Medicare. However, since the Medicare data lags Medicaid, that field is always 0 after the end of the Medicare date range (currently '2016-12-31'), even when the person likely remains a dual (e.g., look at IDs where from_date = '2017-01-01' and contiguous = 1 and mcaid = 1).

We need a way to remove duals from more recent analyses. Can we add another dual column in that keeps the P1/Medicaid dual flag in these timevar tables?

**Comment by alastairmatheson** [comment]
Since we are moving to just using combined mcaid_mcare[_pha]_elig tables, we want all components to come through. Currently missing:
- Language from mcaid (elig_demo)
- Dual (as defined by P1) (elig_timevar)

**Comment by elikern-kc** [comment]
Thanks for pointing this out. I think the idea of keeping the ProviderOne Medicaid dual flag in the mcaid_mcare_elig_timevar table is a great idea.

Best,
Eli

Eli Kern MPH RN | Epidemiologist
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=http%3a%2f%2fwww.kingcounty.gov%2fhealthservices%2fhealth.aspx>
phone: 206.263.8727 | email: eli.kern@kingcounty.gov<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

**Comment by alastairmatheson** [comment]
Dual added to timevar in https://github.com/PHSKC-APDE/claims_data/pull/69/commits/dc01eac34725886dd8218bcc5d9a04754a647497.
Language added to demo in https://github.com/PHSKC-APDE/claims_data/commit/cdec2bc102d131e0f2d4d63a7ae1ccdc5b77e3ce.
