### ISSUE TITLE
in fall of each year, add one more year to rolling_period tables for CCW

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/claims_data#47]
E.g., In fall 2020, add 2021 to 12, 24, and 36-month rolling period tables that are used to generate claim_ccw tables

**Comment by alastairmatheson** [comment]
Tables now run through 2030 as part of https://github.com/PHSKC-APDE/claims_data/commit/a10108d7658958e5961d9197e432e188e4ca6660
