### ISSUE TITLE
a few bugs in claims_elig function

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/claims_data#82]
I tried earlier today to run the claims_elig function with the apcd data and noticed a few bugs in the code. I began to attempt a fix but figured it would be easier for Alastair to fix as he wrote the script:

- line 961: will fail if dual_sql object does not exist, needs branching if/else
-line 445: variable in elig_demo table is called age, right? not age_min
-line 449: same comment for age_max
-line 449: shouldn't operator be <= instead of >=?
-line 454: should be gender_female instead of female
-line 457: should be gender_male instead of male

I fixed the above errors but still couldn't get the function to run on apcd data because the age_min and age_max parameters were attempting to apply to the apcd.elig_demo table, but "age" is created on the fly and thus doesn't exist yet.

**Comment by alastairmatheson** [comment]
Fixed things in https://github.com/PHSKC-APDE/claims_data/pull/84.
I didn't see the issue with dual_sql. If the source is not "mcaid", "mcare", "mcaid_mcare", "mcaid_mcare_pha" (i.e., it's APCD) then dual_sql and associated code should be blank (lines 978-80). I believe the dual field exists in all the names sources so should run ok.
Mcaid- and mcare-only tables don't have a apde_dual field so I updated line 955 (previously it only covered mcare).
